#define ASPNET_GLOBAL_OBJECT                               0
#define ASPNET_APP_OBJECT                                  2
#define ASPNET_APPLICATION_RESTARTS                        4
#define ASPNET_APPLICATIONS_RUNNING                        6
#define ASPNET_REQUESTS_DISCONNECTED                       8
#define ASPNET_REQUEST_EXECUTION_TIME                      10
#define ASPNET_REQUESTS_REJECTED                           12
#define ASPNET_REQUESTS_QUEUED                             14
#define ASPNET_WPS_RUNNING                                 16
#define ASPNET_WPS_RESTARTS                                18
#define ASPNET_REQUEST_WAIT_TIME                           20
#define ASPNET_STATE_SERVER_SESSIONS_ACTIVE                22
#define ASPNET_STATE_SERVER_SESSIONS_ABANDONED             24
#define ASPNET_STATE_SERVER_SESSIONS_TIMED_OUT             26
#define ASPNET_STATE_SERVER_SESSIONS_TOTAL                 28
#define ASPNET_REQUESTS_CURRENT                            30
#define ASPNET_GLOBAL_AUDIT_SUCCESS                        32
#define ASPNET_GLOBAL_AUDIT_FAIL                           34
#define ASPNET_GLOBAL_EVENTS_ERROR                         36
#define ASPNET_GLOBAL_EVENTS_HTTP_REQ_ERROR                38
#define ASPNET_GLOBAL_EVENTS_HTTP_INFRA_ERROR              40
#define ASPNET_REQUESTS_IN_NATIVE_QUEUE                    42
#define ASPNET_ANONYMOUS_REQUESTS                          44
#define ASPNET_ANONYMOUS_REQUESTS_RATE                     46
#define ASPNET_TOTAL_CACHE_ENTRIES                         48
#define ASPNET_TOTAL_CACHE_TURNOVER_RATE                   50
#define ASPNET_TOTAL_CACHE_HITS                            52
#define ASPNET_TOTAL_CACHE_MISSES                          54
#define ASPNET_TOTAL_CACHE_RATIO                           56
#define ASPNET_TOTAL_CACHE_RATIO_BASE                      58
#define ASPNET_API_CACHE_ENTRIES                           60
#define ASPNET_API_CACHE_TURNOVER_RATE                     62
#define ASPNET_API_CACHE_HITS                              64
#define ASPNET_API_CACHE_MISSES                            66
#define ASPNET_API_CACHE_RATIO                             68
#define ASPNET_API_CACHE_RATIO_BASE                        70
#define ASPNET_OUTPUT_CACHE_ENTRIES                        72
#define ASPNET_OUTPUT_CACHE_TURNOVER_RATE                  74
#define ASPNET_OUTPUT_CACHE_HITS                           76
#define ASPNET_OUTPUT_CACHE_MISSES                         78
#define ASPNET_OUTPUT_CACHE_RATIO                          80
#define ASPNET_OUTPUT_CACHE_RATIO_BASE                     82
#define ASPNET_COMPILATIONS                                84
#define ASPNET_DEBUGGING_REQUESTS                          86
#define ASPNET_ERRORS_PRE_PROCESSING                       88
#define ASPNET_ERRORS_COMPILING                            90
#define ASPNET_ERRORS_DURING_REQUEST                       92
#define ASPNET_ERRORS_UNHANDLED                            94
#define ASPNET_ERRORS_UNHANDLED_RATE                       96
#define ASPNET_ERRORS_TOTAL                                98
#define ASPNET_ERRORS_TOTAL_RATE                           100
#define ASPNET_PIPELINES                                   102
#define ASPNET_REQUEST_BYTES_IN                            104
#define ASPNET_REQUEST_BYTES_OUT                           106
#define ASPNET_REQUESTS_EXECUTING                          108
#define ASPNET_REQUESTS_FAILED                             110
#define ASPNET_REQUESTS_NOT_FOUND                          112
#define ASPNET_REQUESTS_NOT_AUTHORIZED                     114
#define ASPNET_REQUESTS_IN_APPLICATION_QUEUE               116
#define ASPNET_REQUESTS_TIMED_OUT                          118
#define ASPNET_REQUESTS_SUCCEDED                           120
#define ASPNET_REQUESTS_TOTAL                              122
#define ASPNET_REQUESTS_TOTAL_RATE                         124
#define ASPNET_SESSIONS_ACTIVE                             126
#define ASPNET_SESSIONS_ABANDONED                          128
#define ASPNET_SESSIONS_TIMED_OUT                          130
#define ASPNET_SESSIONS_TOTAL                              132
#define ASPNET_TRANSACTIONS_ABORTED                        134
#define ASPNET_TRANSACTIONS_COMMITTED                      136
#define ASPNET_TRANSACTIONS_PENDING                        138
#define ASPNET_TRANSACTIONS_TOTAL                          140
#define ASPNET_TRANSACTIONS_RATE                           142
#define ASPNET_SESSION_STATE_SERVER_CONNECTIONS            144
#define ASPNET_SESSION_SQL_SERVER_CONNECTIONS              146
#define ASPNET_EVENTS_TOTAL                                148
#define ASPNET_EVENTS_TOTAL_RATE                           150
#define ASPNET_EVENTS_APP                                  152
#define ASPNET_EVENTS_APP_RATE                             154
#define ASPNET_EVENTS_ERROR                                156
#define ASPNET_EVENTS_ERROR_RATE                           158
#define ASPNET_EVENTS_HTTP_REQ_ERROR                       160
#define ASPNET_EVENTS_HTTP_REQ_ERROR_RATE                  162
#define ASPNET_EVENTS_HTTP_INFRA_ERROR                     164
#define ASPNET_EVENTS_HTTP_INFRA_ERROR_RATE                166
#define ASPNET_EVENTS_WEB_REQ                              168
#define ASPNET_EVENTS_WEB_REQ_RATE                         170
#define ASPNET_AUDIT_SUCCESS                               172
#define ASPNET_AUDIT_FAIL                                  174
#define ASPNET_MEMBER_SUCCESS                              176
#define ASPNET_MEMBER_FAIL                                 178
#define ASPNET_FORMS_AUTH_SUCCESS                          180
#define ASPNET_FORMS_AUTH_FAIL                             182
#define ASPNET_VIEWSTATE_MAC_FAIL                          184
#define ASPNET_APP_REQUEST_EXEC_TIME                       186
#define ASPNET_APP_REQUEST_DISCONNECTED                    188
#define ASPNET_APP_REQUESTS_REJECTED                       190
#define ASPNET_APP_REQUEST_WAIT_TIME                       192
#define ASPNET_CACHE_PERCENT_MACH_MEM_LIMIT_USED           194
#define ASPNET_CACHE_PERCENT_MACH_MEM_LIMIT_USED_BASE      196
#define ASPNET_CACHE_PERCENT_PROC_MEM_LIMIT_USED           198
#define ASPNET_CACHE_PERCENT_PROC_MEM_LIMIT_USED_BASE      200
#define ASPNET_CACHE_TOTAL_TRIMS                           202
#define ASPNET_CACHE_API_TRIMS                             204
#define ASPNET_CACHE_OUTPUT_TRIMS                          206
#define ASPNET_APP_CPU_USED                                208
#define ASPNET_APP_CPU_USED_BASE                           210
#define ASPNET_APP_MEMORY_USED                             212
#define ASPNET_REQUEST_BYTES_IN_WEBSOCKETS                 214
#define ASPNET_REQUEST_BYTES_OUT_WEBSOCKETS                216
#define ASPNET_REQUESTS_EXECUTING_WEBSOCKETS               218
#define ASPNET_REQUESTS_FAILED_WEBSOCKETS                  220
#define ASPNET_REQUESTS_SUCCEEDED_WEBSOCKETS               222
#define ASPNET_REQUESTS_TOTAL_WEBSOCKETS                   224
